version: '3'

services:

  backend:
    build: ./backend/
    container_name: backend
    ports:
      - 8001:8001

  mongodb:
    build: ./mongo/
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000